export const shops = [
  {
    id: 1,
    name: "ADIDAS",
    category: "obuca",
    url: "https://www.adidas.com.tr/en",
    imgUrl: "https://www.adidas.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 2,
    name: "NIKE",
    category: "obuca",
    url: "https://www.nike.com/tr/",
    imgUrl: "https://www.nike.com",
    joinUrl:
      "https://www.nike.com/tr/member/profile/login?continueUrl=https://www.nike.com/tr/",
    image: "",
  },
  {
    id: 3,
    name: "PUMA",
    category: "obuca",
    url: "https://tr.puma.com/",
    imgUrl: "https://tr.puma.com/",
    joinUrl: "https://tr.puma.com/customer/account/login/",
    image: "",
  },
  {
    id: 4,
    name: "REEBOK",
    category: "obuca",
    url: "https://www.reebok.com.tr/",
    imgUrl: "https://www.reebok.com",
    joinUrl: "https://www.reebok.com.tr/uye",
    image: "",
  },
  {
    id: 5,
    name: "BAMBI",
    category: "obuca",
    url: "https://www.bambiayakkabi.com.tr/",
    imgUrl: "https://www.bambiayakkabi.com",
    joinUrl: "https://www.bambiayakkabi.com.tr/UyeGiris",
    image: "",
  },
  {
    id: 6,
    name: "ELLE",
    category: "obuca",
    url: "https://www.elleshoes.com/",
    imgUrl: "https://www.elleshoes.com/",
    joinUrl: "https://www.elleshoes.com/UyeGiris",
    image: "",
  },
  {
    id: 7,
    name: "POLARIS",
    category: "obuca",
    url: "https://www.instagram.com/polarisayakkabi/",
    imgUrl: "",
    joinUrl: "",
    image: "",
  },
  {
    id: 8,
    name: "HAMMER JACK",
    category: "obuca",
    url: "https://www.hammerjack.com/",
    imgUrl: "https://www.hammerjack.com/",
    joinUrl: "https://www.hammerjack.com/UyeGiris",
    image: "",
  },
  {
    id: 9,
    name: "GRAYDER",
    category: "obuca",
    url: "https://www.greyder.com.tr/",
    imgUrl: "https://www.greyder.com",
    joinUrl: "https://www.greyder.com.tr/uye?returnurl=%2fsepet",
    image: "",
  },
  {
    id: 10,
    name: "HOTIC",
    category: "obuca",
    url: "https://www.hotic.com.tr/",
    imgUrl: "https://www.hotic.com",
    joinUrl: "https://www.hotic.com.tr/login",
    image: "",
  },
  {
    id: 11,
    name: "DERIMOD",
    category: "obuca",
    url: "https://www.derimod.com.tr/",
    imgUrl: "https://www.derimod.com",
    joinUrl: "https://www.derimod.com.tr/login/?next=/",
    image: "",
  },
  {
    id: 12,
    name: "INCI",
    category: "obuca",
    url: "https://www.incitopuk.com.tr/",
    imgUrl: "https://www.incitopuk.com",
    joinUrl: "https://www.incitopuk.com.tr/UyeGiris",
    image: "",
  },
  {
    id: 13,
    name: "KINETIX",
    category: "obuca",
    url: "https://www.kinetix.com.tr/",
    imgUrl: "https://www.kinetix.com",
    joinUrl: "https://www.flo.com.tr/customer/login",
    image: "",
  },
  {
    id: 14,
    name: "DOCKERS",
    category: "obuca",
    url: "https://www.dockers.com.tr/",
    imgUrl: "https://www.dockers.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 15,
    name: "VANS",
    category: "obuca",
    url: "https://www.vans.com.tr/",
    imgUrl: "https://www.vans.com",
    joinUrl: "https://www.vans.com.tr/Uye",
    image: "",
  },
  {
    id: 16,
    name: "LOTTO",
    category: "obuca",
    url: "https://www.xn--lottotrkiye-yhb.com/",
    imgUrl: "https://www.xn--lottotrkiye-yhb.com/",
    joinUrl: "https://www.xn--lottotrkiye-yhb.com/create_account.html",
    image: "",
  },
  {
    id: 17,
    name: "CONVERSE",
    category: "obuca",
    url: "https://www.converse.com.tr/",
    imgUrl: "https://www.converse.com",
    joinUrl: "https://www.converse.com.tr/users/register/",
    image: "",
  },
  {
    id: 18,
    name: "SALOMON",
    category: "obuca",
    url: "https://www.salomon.com.tr/",
    imgUrl: "https://www.salomon.com",
    joinUrl: "https://www.salomon.com.tr/UyeGiris",
    image: "",
  },
  {
    id: 19,
    name: "SKECHERS",
    category: "obuca",
    url: "https://www.skechers.com.tr/",
    imgUrl: "https://www.skechers.com",
    joinUrl: "https://www.skechers.com.tr/register",
    image: "",
  },
  {
    id: 20,
    name: "ASICS",
    category: "obuca",
    url: "https://www.asics.com.tr/",
    imgUrl: "https://www.asics.com",
    joinUrl: "https://www.asics.com.tr/register",
    image: "",
  },
  {
    id: 21,
    name: "THE NORTHFACE",
    category: "obuca",
    url: "https://www.thenorthface.com.tr/",
    imgUrl: "https://www.thenorthface.com",
    joinUrl: "https://www.thenorthface.com.tr/Uye/KayitOl",
    image: "",
  },
  {
    id: 22,
    name: "CEYO",
    category: "obuca",
    url: "https://www.ceyo.com.tr/",
    imgUrl: "https://www.ceyo.com",
    joinUrl: "https://www.ceyo.com.tr/ceyo-uye-kayit",
    image: "",
  },
  {
    id: 23,
    name: "SLAZENGER",
    category: "obuca",
    url: "https://www.slazenger.com.tr/",
    imgUrl: "https://www.slazenger.com",
    joinUrl: "https://www.slazenger.com.tr/uye-kayit",
    image: "",
  },
  {
    id: 24,
    name: "FLO",
    category: "obuca",
    url: "https://www.flo.com.tr/",
    imgUrl: "https://www.flo.com",
    joinUrl: "https://www.flo.com.tr/customer/login#register",
    image: "",
  },
  {
    id: 25,
    name: "TIMBERLEND",
    category: "obuca",
    url: "https://www.timberland.com.tr/",
    imgUrl: "https://www.timberland.com",
    joinUrl: "https://www.timberland.com.tr/uye/kayitol",
    image: "",
  },
  {
    id: 26,
    name: "JACK WOLFSKIN",
    category: "obuca",
    url: "www.olgar.com.tr",
    imgUrl: "www.olgar.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 27,
    name: "AYAKKABI DUNYASI",
    category: "obuca",
    url: "https://www.ayakkabidunyasi.com.tr/",
    imgUrl: "https://www.ayakkabidunyasi.com",
    joinUrl: "https://www.ayakkabidunyasi.com.tr/register",
    image: "",
  },
  {
    id: 28,
    name: "ECANTA",
    category: "torbe",
    url: "https://www.ecanta.com.tr/",
    imgUrl: "https://www.ecanta.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 29,
    name: "SAMSONITE",
    category: "torbe",
    url: "https://www.samsonite.com.tr/",
    imgUrl: "https://www.samsonite.com",
    joinUrl: "https://www.samsonite.com.tr/register/?next=/",
    image: "",
  },
  {
    id: 118,
    name: "BOYNER",
    category: "torbe",
    url: "https://www.boyner.com.tr/",
    imgUrl: "https://www.boyner.com",
    joinUrl:
      "https://www.boyner.com.tr/uyelik?type=uye-ol&isguestcheckout=false",
    image: "",
  },
  {
    id: 119,
    name: "TRENDYOL",
    category: "torbe",
    url: "https://www.trendyol.com/",
    imgUrl: "https://www.trendyol.com/",
    joinUrl:
      "https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F",
    image: "",
  },
  {
    id: 30,
    name: "HEPSIBURADA",
    category: "torbe",
    url: "https://www.hepsiburada.com/",
    imgUrl: "https://www.hepsiburada.com/",
    joinUrl:
      "https://giris.hepsiburada.com/?ReturnUrl=https%3A%2F%2Foauth.hepsiburada.com%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSPA%26redirect_uri%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252Fuyelik%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3Dfb85f6b8f62a4121b770393515238147%26code_challenge%3DGLJMuPFpN53KT61jyREpcWqbB-pa-cAzqrCAfP6aHr0%26code_challenge_method%3DS256%26response_mode%3Dquery%26ActivePage%3DSIGN_UP%26oidcReturnUrl%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252F",
    image: "",
  },
  {
    id: 31,
    name: "MORHIPO",
    category: "torbe",
    url: "https://www.morhipo.com/",
    imgUrl: "https://www.morhipo.com/",
    joinUrl: "https://www.morhipo.com/uyelik",
    image: "",
  },
  {
    id: 120,
    name: "TERGAN",
    category: "torbe",
    url: "https://www.tergan.com.tr/",
    imgUrl: "https://www.tergan.com",
    joinUrl: "https://www.tergan.com.tr/login.aspx",
    image: "",
  },
  {
    id: 32,
    name: "TEKNOSA",
    category: "aksesoar",
    url: "https://www.teknosa.com/",
    imgUrl: "https://www.teknosa.com",
    joinUrl: "https://www.teknosa.com/login",
    image: "",
  },
  {
    id: 33,
    name: "TRENDYOL",
    category: "aksesoar",
    url: "https://www.trendyol.com/",
    imgUrl: "https://www.trendyol.com/",
    joinUrl:
      "https://www.trendyol.com/uyelik?cb=https%3A%2F%2Fwww.trendyol.com%2F",
    image: "",
  },
  {
    id: 34,
    name: "HEPSIBURADA",
    category: "aksesoar",
    url: "https://www.hepsiburada.com/",
    imgUrl: "https://www.hepsiburada.com/",
    joinUrl:
      "https://giris.hepsiburada.com/?ReturnUrl=https%3A%2F%2Foauth.hepsiburada.com%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSPA%26redirect_uri%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252Fuyelik%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3Dfb85f6b8f62a4121b770393515238147%26code_challenge%3DGLJMuPFpN53KT61jyREpcWqbB-pa-cAzqrCAfP6aHr0%26code_challenge_method%3DS256%26response_mode%3Dquery%26ActivePage%3DSIGN_UP%26oidcReturnUrl%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252F",
    image: "",
  },
  {
    id: 35,
    name: "VATANBILGISAYAR",
    category: "aksesoar",
    url: "https://www.vatanbilgisayar.com/",
    imgUrl: "https://www.vatanbilgisayar.com/",
    joinUrl:
      "https://www.vatanbilgisayar.com/login/?returnUrl=%2F&logtab=signup",
    image: "",
  },
  {
    id: 36,
    name: "MEDIAMARKT",
    category: "aksesoar",
    url: "https://www.mediamarkt.com.tr/",
    imgUrl: "https://www.mediamarkt.com",
    joinUrl: "EROR NEKI IZBACUJE KAD SE KLIKNE NA REGISTRACIJU",
    image: "",
  },
  {
    id: 37,
    name: "CEPSESUAR",
    category: "aksesoar",
    url: "https://www.cepsesuar.com/",
    imgUrl: "https://www.cepsesuar.com/",
    joinUrl: "https://www.cepsesuar.com/uye-ol",
    image: "",
  },
  {
    id: 38,
    name: "SPIGEN",
    category: "aksesoar",
    url: "https://www.spigen.com.tr/",
    imgUrl: "https://www.spigen.com",
    joinUrl: "https://www.spigen.com.tr/uye-ol",
    image: "",
  },
  {
    id: 39,
    name: "Kılıfmarketim",
    category: "aksesoar",
    url: "https://www.kilifmarketim.com/",
    imgUrl: "https://www.kilifmarketim.com",
    joinUrl: "https://www.kilifmarketim.com/uye-ol",
    image: "",
  },
  {
    id: 40,
    name: "Zen",
    category: "licni",
    url: "https://www.zenpirlanta.com/",
    imgUrl: "https://www.zenpirlanta.com",
    joinUrl: "https://www.zenpirlanta.com/uyelik_giris.php",
    image: "",
  },
  {
    id: 41,
    name: "Bluediomand",
    category: "licni",
    url: "https://www.bluediamond.com.tr/",
    imgUrl: "https://www.bluediamond.com",
    joinUrl: "https://www.bluediamond.com.tr/uyelik.php?islem=uyekayit",
    image: "",
  },
  {
    id: 42,
    name: "Atasay",
    category: "licni",
    url: "https://www.atasay.com/",
    imgUrl: "https://www.atasay.com",
    joinUrl: "https://www.atasay.com/users/auth/",
    image: "",
  },
  {
    id: 43,
    name: "Altınbaş",
    category: "licni",
    url: "https://www.altinbas.com/",
    imgUrl: "https://www.altinbas.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 44,
    name: "Trendyol",
    category: "licni",
    url: "https://www.trendyol.com/",
    imgUrl: "https://www.trendyol.com/",
    joinUrl: "https://www.trendyol.com/",
    image: "",
  },
  {
    id: 45,
    name: "Takıbu",
    category: "licni",
    url: "https://takibu.com/",
    imgUrl: "https://takibu.com",
    joinUrl: "https://takibu.com/user/login",
    image: "",
  },
  {
    id: 46,
    name: "Takıştır",
    category: "licni",
    url: "https://www.takistir.com.tr/",
    imgUrl: "https://www.takistir.com",
    joinUrl: "https://www.takistir.com.tr/UyeGiris",
    image: "",
  },
  {
    id: 47,
    name: "Kozenbijoux",
    category: "licni",
    url: "https://www.kozenbijoux.com/",
    imgUrl: "https://www.kozenbijoux.com",
    joinUrl: "https://www.kozenbijoux.com/hesabim/",
    image: "",
  },
  {
    id: 48,
    name: "Tesbihane",
    category: "licni",
    url: "https://www.tesbihane.com/",
    imgUrl: "https://www.tesbihane.com",
    joinUrl: "https://www.tesbihane.com/uye-kayit",
    image: "",
  },
  {
    id: 49,
    name: "Tesbihevim",
    category: "licni",
    url: "https://www.tesbihevim.com/",
    imgUrl: "https://www.tesbihevim.com",
    joinUrl: "https://www.tesbihevim.com/uye-ol",
    image: "",
  },
  {
    id: 50,
    name: "Aniyuzuk",
    category: "licni",
    url: "https://www.aniyuzuk.com/",
    imgUrl: "https://www.aniyuzuk.com",
    joinUrl: "https://www.aniyuzuk.com/uye-kayit",
    image: "",
  },
  {
    id: 51,
    name: "Atasun",
    category: "naocale",
    url: "www.atasunoptik.com.tr",
    imgUrl: "www.atasunoptik.com",
    joinUrl: "www.atasunoptik.com.tr/Uye",
    image: "",
  },
  {
    id: 52,
    name: "Opmar",
    category: "naocale",
    url: "www.opmar.com.tr",
    imgUrl: "www.opmar.com",
    joinUrl: "www.opmar.com.tr/UyeOl",
    image: "",
  },
  {
    id: 53,
    name: "Shopsolaris",
    category: "naocale",
    url: "www.shopsolaris.com",
    imgUrl: "www.shopsolaris.com",
    joinUrl: "www.shopsolaris.com/customer/account/login",
    image: "",
  },
  {
    id: 54,
    name: "Elitoptik",
    category: "naocale",
    url: "www.elitoptik.com.tr",
    imgUrl: "www.elitoptik.com",
    joinUrl: "www.elitoptik.com.tr/UyeOl",
    image: "",
  },
  {
    id: 55,
    name: "sunglasshut",
    category: "naocale",
    url: "www.sunglasshut.com/uk",
    imgUrl: "www.sunglasshut.com",
    joinUrl: "www.sunglasshut.com/uk/myaccount/login?redirect=%2Fmyaccount",
    image: "",
  },
  {
    id: 56,
    name: "Garajmarketim",
    category: "auto",
    url: "www.garajmarketim.com",
    imgUrl: "www.garajmarketim.com",
    joinUrl: "www.garajmarketim.com/UyeOl",
    image: "",
  },
  {
    id: 57,
    name: "Otoaksesuar",
    category: "auto",
    url: "www.otoaksesuar.com",
    imgUrl: "www.otoaksesuar.com",
    joinUrl: "www.otoaksesuar.com/uye-kayit",
    image: "",
  },
  {
    id: 58,
    name: "Aksoytuning",
    category: "auto",
    url: "www.aksoytuning.com",
    imgUrl: "www.aksoytuning.com",
    joinUrl: "www.aksoytuning.com/ac/register",
    image: "",
  },
  {
    id: 59,
    name: "Hepsiburada",
    category: "auto",
    url: "www.hepsiburada.com/oto-aksesuarlari-c-2147483631",
    imgUrl: "www.hepsiburada.com",
    joinUrl:
      "giris.hepsiburada.com/?ReturnUrl=https%3A%2F%2Foauth.hepsiburada.com%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3DSPA%26redirect_uri%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252Fuyelik%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%26state%3D1913e348742b4ebaaf475bfff381d12b%26code_challenge%3DwF76Wth970-_Alfh2RlLqIcxx3FsiX1fbPosx5HClOM%26code_challenge_method%3DS256%26response_mode%3Dquery%26ActivePage%3DSIGN_UP%26oidcReturnUrl%3Dhttps%253A%252F%252Fwww.hepsiburada.com%252F",
    image: "",
  },
  {
    id: 60,
    name: "Trendyol",
    category: "auto",
    url: "www.trendyol.com/otomobil-ve-motosiklet-x-c105777",
    imgUrl: "www.trendyol.com",
    joinUrl: "https://www.trendyol.com/",
    image: "",
  },
  {
    id: 61,
    name: "Mediamarkt",
    category: "elektronika",
    url: "www.mediamarkt.com.tr",
    imgUrl: "www.mediamarkt.com",
    joinUrl:
      "www.mediamarkt.com.tr/webapp/wcs/stores/servlet/MultiChannelMARegister?storeId=20201&langId=-14&redirectURL=http%3A%2F%2Fwww.mediamarkt.com.tr%2F",
    image: "",
  },
  {
    id: 62,
    name: "Teknosa",
    category: "elektronika",
    url: "www.teknosa.com",
    imgUrl: "www.teknosa.com",
    joinUrl: "www.teknosa.com/login",
    image: "",
  },
  {
    id: 63,
    name: "Vatanbilgisayar",
    category: "elektronika",
    url: "www.vatanbilgisayar.com",
    imgUrl: "www.vatanbilgisayar.com",
    joinUrl: "www.vatanbilgisayar.com/login/?returnUrl=%2F&logtab=signin",
    image: "",
  },
  {
    id: 64,
    name: "Evkur",
    category: "elektronika",
    url: "www.evkur.com.tr",
    imgUrl: "www.evkur.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 65,
    name: "GRATIS",
    category: "kozmetika",
    url: "www.gratis.com",
    imgUrl: "www.gratis.com",
    joinUrl: "www.gratis.com/sign-up",
    image: "",
  },
  {
    id: 66,
    name: "WATSONS",
    category: "kozmetika",
    url: "www.watsons.com.tr",
    imgUrl: "www.watsons.com",
    joinUrl: "www.watsons.com.tr/register",
    image: "",
  },
  {
    id: 67,
    name: "ROSSMANN",
    category: "kozmetika",
    url: "www.rossmann.com.tr",
    imgUrl: "www.rossmann.com",
    joinUrl: "www.rossmann.com.tr/customer/account/create/",
    image: "",
  },
  {
    id: 68,
    name: "PLATIN",
    category: "kozmetika",
    url: "www.platin.com.tr",
    imgUrl: "www.platin.com",
    joinUrl: "www.platin.com.tr/UyeOl",
    image: "",
  },
  {
    id: 69,
    name: "SEPHORA",
    category: "kozmetika",
    url: "www.sephora.com.tr",
    imgUrl: "www.sephora.com",
    joinUrl: "www.sephora.com.tr/giris-yap",
    image: "",
  },
  {
    id: 70,
    name: "MAC",
    category: "kozmetika",
    url: "www.maccosmetics.com.tr",
    imgUrl: "www.maccosmetics.com",
    joinUrl: "www.maccosmetics.com.tr/account/registration.tmpl",
    image: "",
  },
  {
    id: 71,
    name: "THE BODY SHOP",
    category: "kozmetika",
    url: "www.thebodyshop.com.tr",
    imgUrl: "www.thebodyshop.com",
    joinUrl: "www.thebodyshop.com.tr/UyeGiris",
    image: "",
  },
  {
    id: 72,
    name: "AVON",
    category: "kozmetika",
    url: "kozmetik.avon.com.tr/?gclid=CjwKCAjwiOCgBhAgEiwAjv5whNUvk0uBUZDJqun06PwbzxmF5nvD7wjntwNABgtwH583O0ufw3lvbBoCfacQAvD_BwE&gclsrc=aw.ds",
    imgUrl: "kozmetik.avon.com",
    joinUrl: "kozmetik.avon.com.tr/musteri/oturum-ac/",
    image: "",
  },
  {
    id: 73,
    name: "COSMETICA",
    category: "kozmetika",
    url: "www.cosmetica.com.tr",
    imgUrl: "www.cosmetica.com",
    joinUrl: "www.cosmetica.com.tr/login.aspx?signup=true",
    image: "",
  },
  {
    id: 74,
    name: "IKEA",
    category: "kucni aparati",
    url: "www.ikea.com.tr",
    imgUrl: "www.ikea.com",
    joinUrl: "www.ikea.com.tr/uyelik/yeni-uyelik",
    image: "",
  },
  {
    id: 75,
    name: "TepeHome",
    category: "kucni aparati",
    url: "www.tepehome.com.tr",
    imgUrl: "www.tepehome.com",
    joinUrl: "www.tepehome.com.tr/uye-kayit",
    image: "",
  },
  {
    id: 76,
    name: "MUDO",
    category: "kucni aparati",
    url: "www.mudo.com.tr/?gclid=CjwKCAjwiOCgBhAgEiwAjv5whPg6QnbWfub-Q6Rv6ej-fDrA3IaiDuE0Dp8zfz6Nbs1-b7WGEsR_kRoCCVkQAvD_BwE",
    imgUrl: "www.mudo.com",
    joinUrl: "www.mudo.com.tr/register/?next=/",
    image: "",
  },
  {
    id: 77,
    name: "Englishhome",
    category: "kucni aparati",
    url: "www.englishhome.com",
    imgUrl: "www.englishhome.com",
    joinUrl: "www.englishhome.com/login/?next=/",
    image: "",
  },
  {
    id: 78,
    name: "Özdilek",
    category: "kucni aparati",
    url: "www.ozdilek.com.tr",
    imgUrl: "www.ozdilek.com",
    joinUrl: "www.ozdilekteyim.com/magaza/login/register",
    image: "",
  },
  {
    id: 79,
    name: "Karaca",
    category: "kucni aparati",
    url: "www.karaca.com",
    imgUrl: "www.karaca.com",
    joinUrl: "www.karaca.com/account/login",
    image: "",
  },
  {
    id: 80,
    name: "Koçtaş",
    category: "kucni aparati",
    url: "www.koctas.com.tr",
    imgUrl: "www.koctas.com",
    joinUrl: "www.koctas.com.tr/sregister/register",
    image: "",
  },
  {
    id: 81,
    name: "Tekzen",
    category: "kucni aparati",
    url: "www.tekzen.com.tr",
    imgUrl: "www.tekzen.com",
    joinUrl: "www.tekzen.com.tr/giris?type=kayit",
    image: "",
  },
  {
    id: 82,
    name: "ZARA",
    category: "odjeca",
    url: "https://www.zara.com/tr/",
    imgUrl: "https://www.zara.com",
    joinUrl: "https://www.zara.com/tr/en/signup",
    image: "",
  },
  {
    id: 83,
    name: "LC WAIKIKI",
    category: "odjeca",
    url: "https://www.lcwaikiki.com/tr-TR/TR",
    imgUrl: "https://www.lcwaikiki.com",
    joinUrl: "https://www.lcwaikiki.com/tr-TR/TR/uye-ol",
    image: "",
  },
  {
    id: 84,
    name: "MAVI",
    category: "odjeca",
    url: "www.mavi.com",
    imgUrl: "www.mavi.com",
    joinUrl: " https://www.mavi.com/register",
    image: "",
  },
  {
    id: 85,
    name: "MANGO",
    category: "odjeca",
    url: "https://shop.mango.com/tr/kadin",
    imgUrl: "https://shop.mango.com/",
    joinUrl:
      "https://shop.mango.com/login.faces?state=she_052_TR&ts=1674985709817",
    image: "",
  },
  {
    id: 86,
    name: "POLO",
    category: "odjeca",
    url: "https://tr.uspoloassn.com/",
    imgUrl: "https://tr.uspoloassn.com",
    joinUrl: "https://tr.uspoloassn.com/register/",
    image: "",
  },
  {
    id: 87,
    name: "DAMAT",
    category: "odjeca",
    url: "https://www.dsdamat.com/",
    imgUrl: "https://www.dsdamat.com",
    joinUrl: "https://www.dsdamat.com/users/register/",
    image: "",
  },
  {
    id: 88,
    name: "PULL AND BEAR",
    category: "odjeca",
    url: "www.pullandbear.com/tr",
    imgUrl: "www.pullandbear.com",
    joinUrl: "https://www.pullandbear.com/tr/login.html",
    image: "",
  },
  {
    id: 89,
    name: "BERSHKA",
    category: "odjeca",
    url: "https://www.bershka.com/tr/",
    imgUrl: "https://www.bershka.com",
    joinUrl: "",
    image: "",
  },
  {
    id: 90,
    name: "BEYMEN",
    category: "odjeca",
    url: "https://www.beymen.com/",
    imgUrl: "https://www.beymen.com",
    joinUrl:
      "https://www.beymen.com/customer/register?returnUrl=/customer/order",
    image: "",
  },
  {
    id: 91,
    name: "DEFACTO",
    category: "odjeca",
    url: "https://www.defacto.com.tr/",
    imgUrl: "https://www.defacto.com",
    joinUrl: " https://www.defacto.com.tr/Login?newUser=True&ReturnUrl=%2F",
    image: "",
  },
  {
    id: 92,
    name: "MUDO",
    category: "odjeca",
    url: "https://www.mudo.com.tr/",
    imgUrl: "https://www.mudo.com",
    joinUrl: "https://www.mudo.com.tr/register/",
    image: "",
  },
  {
    id: 93,
    name: "KOTON",
    category: "odjeca",
    url: "https://www.koton.com/",
    imgUrl: "https://www.koton.com",
    joinUrl: "https://www.koton.com/users/auth/",
    image: "",
  },
  {
    id: 94,
    name: "TERGAN",
    category: "odjeca",
    url: "https://www.tergan.com.tr/",
    imgUrl: "https://www.tergan.com",
    joinUrl: "https://www.tergan.com.tr/login.aspx",
    image: "",
  },
  {
    id: 95,
    name: "IPEKYOL",
    category: "odjeca",
    url: "https://www.ipekyol.com.tr/",
    imgUrl: "https://www.ipekyol.com",
    joinUrl: "https://www.ipekyol.com.tr/giris?returnUrl=&member=signup",
    image: "",
  },
  {
    id: 96,
    name: "KIGILI",
    category: "odjeca",
    url: "https://www.kigili.com/",
    imgUrl: "https://www.kigili.com",
    joinUrl: "https://www.kigili.com/register/?next=/",
    image: "",
  },
  {
    id: 97,
    name: "Ebebek",
    category: "odjeca",
    url: "https://www.e-bebek.com/",
    imgUrl: "https://www.e-bebek.com",
    joinUrl: "https://www.e-bebek.com/login",
    image: "",
  },
  {
    id: 98,
    name: "Joker",
    category: "odjeca",
    url: "https://www.joker.com.tr/",
    imgUrl: "https://www.joker.com",
    joinUrl: "https://www.joker.com.tr/kullanici/kayit",
    image: "",
  },
  {
    id: 99,
    name: "Civilim",
    category: "odjeca",
    url: "https://www.civilim.com/",
    imgUrl: "https://www.civilim.com",
    joinUrl: "https://www.civilim.com/login.aspx",
    image: "",
  },
  {
    id: 100,
    name: "AVVA",
    category: "odjeca",
    url: "https://www.avva.com.tr/",
    imgUrl: "https://www.avva.com",
    joinUrl: "https://www.avva.com.tr/",
    image: "",
  },
  {
    id: 101,
    name: "SARAR",
    category: "odjeca",
    url: "https://sarar.com/",
    imgUrl: "https://sarar.com",
    joinUrl: "https://sarar.com/uye-kayit",
    image: "",
  },
  {
    id: 102,
    name: "LEVI’S",
    category: "odjeca",
    url: "https://www.levis.com.tr/",
    imgUrl: "https://www.levis.com.tr",
    joinUrl: "https://www.levis.com.tr/",
    image: "",
  },
  {
    id: 103,
    name: "CALVIN KLEIN",
    category: "odjeca",
    url: "https://tr.calvinklein.com/",
    imgUrl: "https://tr.calvinklein.com",
    joinUrl: "https://tr.calvinklein.com/",
    image: "",
  },
  {
    id: 104,
    name: "LOFT",
    category: "odjeca",
    url: "https://www.loft.com.tr/tr-TR",
    imgUrl: "https://www.loft.com",
    joinUrl: "https://www.loft.com.tr/tr-TR/auth/register",
    image: "",
  },
  {
    id: 105,
    name: "JACK AND JONES",
    category: "odjeca",
    url: "www.jackjones.com.tr",
    imgUrl: "www.jackjones.com",
    joinUrl: "https://jackjones.com.tr/uye-ol",
    image: "",
  },
  {
    id: 106,
    name: "LACOSTE",
    category: "odjeca",
    url: "https://www.lacoste.com.tr/",
    imgUrl: "https://www.lacoste.com",
    joinUrl: "https://www.lacoste.com.tr/register/",
    image: "",
  },
  {
    id: 107,
    name: "GAP",
    category: "odjeca",
    url: "https://gap.com.tr/",
    imgUrl: "https://gap.com",
    joinUrl: "https://gap.com.tr/login/?next=/ ",
    image: "",
  },
  {
    id: 108,
    name: "TOMMY HILFIGER",
    category: "odjeca",
    url: "https://tr.tommy.com/",
    imgUrl: "https://tr.tommy.com",
    joinUrl: "https://tr.tommy.com/ ",
    image: "",
  },
  {
    id: 109,
    name: "ARMINE",
    category: "odjeca",
    url: "https://www.armine.com/",
    imgUrl: "https://www.armine.com",
    joinUrl: "https://www.armine.com/UyeOl ",
    image: "",
  },
  {
    id: 110,
    name: "TEKBIR",
    category: "odjeca",
    url: "https://www.tekbir.com.tr/",
    imgUrl: "https://www.tekbir.com",
    joinUrl: "https://www.tekbir.com.tr/ ",
    image: "",
  },
  {
    id: 111,
    name: "AKER",
    category: "odjeca",
    url: "https://www.aker.com.tr/",
    imgUrl: "https://www.aker.com",
    joinUrl: "https://www.aker.com.tr/uye-kayit",
    image: "",
  },
  {
    id: 112,
    name: "PENTİ",
    category: "odjeca",
    url: "https://www.penti.com/tr/",
    imgUrl: "https://www.penti.com",
    joinUrl: "https://www.penti.com/tr/register ",
    image: "",
  },
  {
    id: 113,
    name: "H and M",
    category: "odjeca",
    url: "https://www2.hm.com/tr_tr/index.html",
    imgUrl: "https://www2.hm.com",
    joinUrl: "https://www2.hm.com/tr_tr/index.html ",
    image: "",
  },
  {
    id: 114,
    name: "ADIDAS",
    category: "odjeca",
    url: "https://www.adidas.com.tr/tr",
    imgUrl: "https://www.adidas.com",
    joinUrl: "https://www.adidas.com.tr/tr ",
    image: "",
  },
  {
    id: 115,
    name: "NIKE",
    category: "odjeca",
    url: "https://www.nike.com/tr",
    imgUrl: "https://www.nike.com",
    joinUrl:
      "https://www.nike.com/tr/member/profile/login?continueUrl=https://www.nike.com/tr/uyelik",
    image: "",
  },
  {
    id: 116,
    name: "PUMA",
    category: "odjeca",
    url: "https://tr.puma.com/",
    imgUrl: "https://tr.puma.com",
    joinUrl: "https://tr.puma.com/customer/account/login/ ",
    image: "",
  },
  {
    id: 117,
    name: "REEBOK",
    category: "odjeca",
    url: "https://www.reebok.com.tr/",
    imgUrl: "https://www.reebok.com",
    joinUrl: "https://www.reebok.com.tr/Uye/signin ",
    image: "",
  },
];
