import Footer from "./components/sections/Footer";
import Header from "./components/sections/Header";
import "./globals.css";

export const metadata = {
  title: "KOLETO Online Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
